class Reciters {
  List reciters = [
    {
      'reciter_name': 'Mishary bin Rashid Alafasy',
      'short_name': 'Alafasy',
      'born': 'September 5, 1976',
      'birth_city': 'Kuwait City, Kuwait',
      'died': '',
      'death_city': '',
      'genre': 'Islamic, Nasheed, Hamd, Na\'at, Qirat',
      'occupation': 'Qari, imam',
      'image': 'images/reciter_images/alafasy.png',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Abdul Rahman Al-Sudais',
      'short_name': 'Sudais',
      'born': '1962',
      'birth_city': 'Riyadh, Saudi Arabia',
      'died': "",
      'death_city': '',
      'genre': '',
      'occupation': 'Qari , Imam',
      'image': 'images/reciter_images/sudais.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Abdul Basit Muhammad Abdus Samad',
      'short_name': 'AbdulBaset',
      'born': '1927',
      'birth_city': 'Armant, Egypt',
      'died': '1988(aged 60–61)',
      'death_city': 'Cairo, Egypt',
      'genre': '',
      'occupation': 'Qari , Imam , Sheikh',
      'image': 'images/reciter_images/basit.jpg',
      'recitation_style_2': 'Murattal',
      'recitation_style_1': 'Mujawwad',
    },
    {
      'reciter_name': 'Mahmoud Khalil Al-Hussary',
      'short_name': 'Husary',
      'born': 'September 17, 1917',
      'birth_city': 'Shobra al-Namla, Tanta, Egypt',
      'died': 'November 24, 1980 (aged 63)',
      'death_city': 'Cairo, Egypt',
      'genre': 'Islamic, Nasheed, Hamd, Na\'at, Qirat',
      'occupation': 'Qari, imam',
      'image': 'images/reciter_images/hussary.png',
      'recitation_style_2': 'Murattal',
      'recitation_style_1': 'Mujawwad',
    },
    {
      'reciter_name': 'Saud Al-Shuraim',
      'short_name': 'Shuraym',
      'born': 'October 15, 1966',
      'birth_city': 'Riyadh, Saudi Arabia',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/shuraym.png',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Muhammad Jibreel',
      'short_name': 'Jibreel',
      'born': '1964',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/jibreel.png',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Khalifa Al Tunaiji',
      'short_name': 'Tunaiji',
      'born': '',
      'birth_city': 'Emirate of Sharjah',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/tunaiji.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Yasser Ad-Dussary',
      'short_name': 'Yasser_Ad-Dussary',
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Yasser_Ad-Dussary.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Ibrahim Al-Dosary',
      'short_name': 'Ibrahim_Al-Dosary',
      'born': '1965',
      'birth_city': 'Riyadh, Saudi Arabia',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Ibrahim_Al-Dosary.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Yassin Al-Jazaery',
      'short_name': 'Yassin_Al-Jazaery',
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Yassin_Al-Jazaery.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Abdullaah 3awwaad Al-Juhaynee',
      'short_name': 'Abdullaah_3awwaad_Al-Juhaynee',
      'born': '13 January 1976',
      'birth_city': 'Medina, Saudi Arabia',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Abdullaah_3awwaad_Al-Juhaynee.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Abdullah Matroud',
      'short_name': 'Abdullah_Matroud',
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Abdullah_Matroud.png',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Ahmed Ibn Ali Al Ajamy',
      'short_name': 'Ahmed_Ibn_Ali_Al_Ajamy',
      'born': '24 February 1968',
      'birth_city': 'Saudi',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': 'Qari',
      'image': 'images/reciter_images/Ahmed_Ibn_Ali_Al-Ajamy.png',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Ahmed Neana',
      'short_name': 'Ahmed_Neana',
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Ahmed_Neana.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Akram Al Alaqimy',
      'short_name': 'Akram_Al_Alaqimy',
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Akram_Al_Alaqimy.png',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Ali Jaber',
      'short_name': 'Ali_Jaber',
      'born': '14 January 2021',
      'birth_city': 'Jeddah, Saudi Arabia',
      'died': '13 December 2005',
      'death_city': 'Jeddah, Saudi Arabia',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Ali_Jaber.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Ali Hajjaj AlSuesy',
      'short_name': 'Ali_Hajjaj_AlSuesy',
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Ali_Hajjaj_AlSuesy.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Ayman Sowaid',
      'short_name': 'Ayman_Sowaid',
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Ayman_Sowaid.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Fares Abbad',
      'short_name': 'Fares_Abbad',
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Fares_Abbad.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Hudhaify',
      'short_name': 'Hudhaify',
      'born': '22 May 1947',
      'birth_city': 'Saudi Arabia',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Hudhaify.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Ibrahim Akhdar',
      'short_name': 'Ibrahim_Akhdar',
      'born': '1945',
      'birth_city': 'Al-Medina, Saudi Arabia.',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Ibrahim_Akhdar.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Karim Mansoori',
      'short_name': 'Karim_Mansoori',
      'born': '1968',
      'birth_city': 'Abadan, Iran',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Karim_Mansoori.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Khalid Abdullah al-Qahtanee',
      'short_name': 'Khalid_Abdullah_al-Qahtanee',
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Khalid_Abdullah_al-Qahtanee.png',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Maher Al Muaiqly',
      'short_name': 'Maher_Al_Muaiqly',
      'born': '7 January 1969',
      'birth_city': 'Medina, Saudi Arabia',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Maher_Al_Muaiqly.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Mahmoud Ali Al-Banna',
      'short_name': 'Mahmoud_Ali_Al-Banna',
      'born': '17 December 1926',
      'birth_city': 'Shubra Bas, Egypt',
      'died': '20 July 1985',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Mahmoud_Ali_Al-Banna.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Minshawi',
      'short_name': 'Minshawi',
      'born': 'January 20, 1920',
      'birth_city': 'Al Minshah, Sohag Governorate, Egypt',
      'died': 'June 20, 1969',
      'death_city': 'Cairo, Egypt',
      'genre': '',
      'occupation': 'Scholar, Author, Qari',
      'image': 'images/reciter_images/Menshawi.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Mohammad al Tablaway',
      'short_name': 'Mohammad_al_Tablaway',
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Mohammad_al_Tablaway.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Muhammad AbdulKareem',
      'short_name': 'Muhammad_AbdulKareem',
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Muhammad_AbdulKareem.png',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Muhammad Ayyoub',
      'short_name': 'Muhammad_Ayyoub',
      'born': '1951',
      'birth_city': 'Mecca, Saudi Arabia',
      'died': '16 April 2016 (aged 65)',
      'death_city': 'Medina, Saudi Arabia',
      'genre': '',
      'occupation': 'Imam, Qari, Islamic scholar',
      'image': 'images/reciter_images/Muhammad_Ayyoub.jpeg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Muhsin Al Qasim',
      'short_name': 'Muhsin_Al_Qasim',
      'born': '1967',
      'birth_city': 'Makkah al-Mukarramah, Saudi Arabia',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Muhsin_Al_Qasim.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Nabil Rifa3i',
      'short_name': 'Nabil_Rifa3i',
      'born': '',
      'birth_city': 'Jeddah, Saudi Arabia',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Nabil_Rifa3i.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Nasser Alqatami',
      'short_name': 'Nasser_Alqatami',
      'born': '1980',
      'birth_city': 'Saudi Arabia',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Nasser_Alqatami.png',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Parhizgar',
      'short_name': 'Parhizgar',
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Parhizgar.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Sahl Yassin',
      'short_name': 'Sahl_Yassin',
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Sahl_Yassin.png',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Salaah AbdulRahman Bukhatir',
      'short_name': 'Salaah_AbdulRahman_Bukhatir',
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Salaah_AbdulRahman_Bukhatir.png',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Salah Al Budair',
      'short_name': 'Salah_Al_Budair',
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Salah_Al_Budair.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Yaser Salamah',
      'short_name': 'Yaser_Salamah',
      'born': '7 January 1970',
      'birth_city': 'Hofuf, Saudi Arabia',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Yaser_Salamah.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
  ];

  //reciters with mistake data starts here
  //
  //
  List recitersWithMistakes = [
    {
      'reciter_name': 'Abdullah Basfar',
      'short_name': 'Abdullah_Basfar',
      'mistakes': [
        {
          'surah_number': 11,
          'verse_number': 82,
        },
        {
          'surah_number': 61,
          'verse_number': 11,
        },
        {
          'surah_number': 61,
          'verse_number': 12,
        },
        {
          'surah_number': 61,
          'verse_number': 13,
        },
        {
          'surah_number': 61,
          'verse_number': 14,
        },
      ],
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Abdullah_Basfar.png',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Abu Bakr Ash-Shaatree',
      'short_name': 'Abu_Bakr_Ash-Shaatree',
      'mistakes': [
        {
          'surah_number': 22,
          'verse_number': 52,
        },
      ],
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Abu_Bakr_Ash_Shaatree.png',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Aziz Alili',
      'short_name': 'Aziz_Alili',
      'mistakes': [
        {
          'surah_number': 23,
          'verse_number': 51,
        },
        {
          'surah_number': 28,
          'verse_number': 25,
        },
      ],
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Aziz_Alili.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Ghamadi',
      'short_name': 'Ghamadi',
      'mistakes': [
        {
          'surah_number': 4,
          'verse_number': 94,
        },
        {
          'surah_number': 16,
          'verse_number': 29,
        },
        {
          'surah_number': 59,
          'verse_number': 24,
        },
      ],
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Ghamadi.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Hani Rifai',
      'short_name': 'Hani_Rifai',
      'mistakes': [
        {
          'surah_number': 24,
          'verse_number': 58,
        },
        {
          'surah_number': 31,
          'verse_number': 27,
        },
      ],
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Hani_Rifai.png',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'reciter_name': 'Minshawy',
      'short_name': 'Minshawy',
      //mistakes are only in Mujawwad
      'mistakes': [
        {
          'surah_number': 4,
          'verse_number': 8,
        },
        {
          'surah_number': 7,
          'verse_number': 63,
        },
        {
          'surah_number': 7,
          'verse_number': 163,
        },
        {
          'surah_number': 20,
          'verse_number': 90,
        },
        {
          'surah_number': 27,
          'verse_number': 70,
        },
        {
          'surah_number': 32,
          'verse_number': 24,
        },
        {
          'surah_number': 39,
          'verse_number': 57,
        },
        {
          'surah_number': 40,
          'verse_number': 62,
        },
        {
          'surah_number': 42,
          'verse_number': 26,
        },
      ],
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Menshawi.jpg',
      'recitation_style_2': 'Murattal',
      'recitation_style_1': 'Mujawwad',
    },
  ];

  //translation data starts here================

  List translations = [
    {
      'translations_name': 'Sahih International',
      //here the reciter name means the person who is reciting the translation
      'reciter_name': 'Sahih International \n (only Translation)',
      'short_name': 'Sahih_International',
      'Translated_by': "Sahih International",
      'recited_by': 'Ibrahim Walk',
      'language': 'English',

      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Sahih_International.png',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'translations_name': 'Farhat Hashmi',
//here the reciter name means the person who is reciting the translation
      'reciter_name': 'Farhat Hashmi',
      'short_name': 'Farhat_Hashmi',
      'Translated_by': "Farhat_Hashmi",
      'recited_by': '',
      'language': "Urdu",
      'born': '22 December 1957',
      'birth_city': 'Sargodha, Pakistan',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Farhat_Hashmi.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'translations_name': 'Shamshad Ali Khan',
//here the reciter name means the person who is reciting the translation
      'reciter_name': 'Shamshad Ali Khan',
      'short_name': 'Shamshad_Ali_Khan',
      'Translated_by': "Shamshad Ali Khan",
      'recited_by': '',
      'language': "Urdu",
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Urdu.png',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'translations_name': 'Makarem',
//here the reciter name means the person who is reciting the translation
      'reciter_name': 'Naser Makarem Shirazi',
      'short_name': 'Makarem',
      'Translated_by': "Makarem",
      'recited_by': 'Kabiri',
      'language': "Persian",
      'born': '25 February 1927',
      'birth_city': 'Shiraz, Iran',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Makarem.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'translations_name': 'Besim Korkut',
//here the reciter name means the person who is reciting the translation
      'reciter_name': 'Besim Korkut',
      'short_name': 'Besim_Korkut',
      'Translated_by': "Besim Korkut",
      'recited_by': '',
      'language': "Bosnian",
      'born': '25 June 1904',
      'birth_city': '',
      'died': '2 November 1975',
      'death_city': 'Sarajevo, Bosnia and Herzegovina',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Besim_Korkut.jpg',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'translations_name': 'Fooladvand',
      //here the reciter name means the person who is reciting the translation
      'reciter_name': 'Fooladvand',
      'short_name': 'Fooladvand',
      'Translated_by': "Fooladvand",
      'recited_by': 'Hedayatfar',
      'language': "Persian",
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Persian.png',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
    {
      'translations_name': 'Balayev',
//here the reciter name means the person who is reciting the translation
      'reciter_name': 'Balayev',
      'short_name': 'Balayev',
      'Translated_by': "Balayev",
      'recited_by': '',
      'language': "Azerbaijani",
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Azerbaijani.png',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
  ];

  List translationsWithMistakes = [
    {
      'translations_name': 'Sahih International with recitation',
      //here the reciter name means the person who is reciting the translation
      'reciter_name': 'Sahih International \n (Translation with recitation)',
      'short_name': 'Sahih_International_with_recitation',
      'Translated_by': "Sahih International",
      'recited_by': 'Ibrahim Walk',
      'language': 'English',
      'mistakes': [
        {
          'surah_number': 19,
          'verse_number': 75,
        },
        {
          'surah_number': 61,
          'verse_number': 6,
        },
        {
          'surah_number': 61,
          'verse_number': 9,
        },
      ],
      'born': '',
      'birth_city': '',
      'died': '',
      'death_city': '',
      'genre': '',
      'occupation': '',
      'image': 'images/reciter_images/Sahih_International.png',
      'recitation_style_1': '',
      'recitation_style_2': '',
    },
  ];
}
