

rasool_allah_names_arabic = [
    'مُحَمَّدٌ',
    'اَحمَدٌ',
    'حَامِدٌ',
    'مَحمُودٌ',
    'قَاسِمٌ',
    'عَاقِبٌ',
    'فَاتَحٌ',
    'شَاهِدٌ',
    'حَاشِرٌ',
    'رَشِدٌ',
    'مَشهُودٌ',
    'بَشِیرٌ',
    'نَزِیرٌ',
    'دَاعً',
    'شَافٍ',
    'هادٍ',
    'مهدٍ',
    'مَاحٍ',
    'مُنجٍ',
    'نَاهٍ',
    'رَسُولٌ',
    'نَبِىٌ',
    'اُمِّىٌ',
    'تِهَامِىٌ',
    'هَاشَمِىٌ',
    'اَبطَحِىٌ',
    'عَزِيزٌ',
    'حَرِيصٌ عَلَيكُم',
    'رءُوفٌ',
    'رَحِيمٌ',
    'طٰهٰ',
    'مُجتَبىٰ',
    'طٰسٓ',
    'مُرتَظٰى',
    'حٰمٓ',
    'مُصطَفىٰ',
    'يٰسٓ',
    'اَولىٰ',
    'مُزَّمِلٌ',
    'وَلِىٌ',
    'مُدَّثِّرٌ',
    'مَتِينٌ',
    'مُصَدِّقٌ',
    'طَيِّبٌ',
    'نَاصِرٌ',
    'مَنصُورٌ',
    'مِصبَاحٌ',
    'اٰمِرٌ',
    'حِجَازِىٌ',
    'نَزَارِىٌ',
    'قَرَشِىٌ',
    'مُضَرِىٌ',
    'نَبِىُّ التُّوبَة',
    'حَافِظٌ',
    'كَامِلٌ',
    'صَادِقٌ',
    'اَمِينٌ',
    'عَبدُاللّٰه',
    'كَلِيمُ اللّٰه',
    'حَبَيبُ اللّٰه',
    'نَجَىُّ اللّٰه',
    'صَفِىٌ اللّٰه',
    'خَاتِمُ الانَبِيآء,',
    'حَسِيبٌ',
    'مُجِيبٌ',
    'شَكُورٌ',
    'مُقتَصِدٌ',
    'رَسُولُ الرَّحمَةِ',
    'قَوِىٌ',
    'حَفِىٌ',
    'مَامُونٌ',
    'مَعلُومٌ',
    'حَقٌ',
    'مُبِينٌ',
    'مُطِيعٌ',
    'اَوَّلٌ',
    'اٰخِرٌ',
    'ظَاهِرٌ',
    'بَاطِنٌ',
    'يَتِيمٌ',
    'كَرِيمٌ',
    'حَكِيمٌ',
    'سَيِّدٌ',
    'سِرَاجٌ',
    'مُنِيرٌ',
    'مُحَرَّمٌ',
    'مُكَرَّمٌ',
    'مُبَشِرٌ',
    'مُزَكِّرٌ',
    'مُطَهَّرٌ',
    'قَريِبٌ',
    'خَلِيلٌ',
    'مَدعُوٌ',
    'جَوَّادٌ',
    'خَاتِمٌ',
    'عَادِلٌ',
    'شَهَيرٌ',
    'شَهَيدٌ',
    'رَسولٌ المَلَا حِمِ',
]


rasool_allah_names_english = [
    'Muhammad',
    'Ahmad',
    'Hamid',
    'Mahmud',
    'Qaasim',
    'Aqib',
    'Faateh',
    'Shahid',
    'Hashir',
    'Rash?d',
    'Mashhood',
    'Basheer',
    'Ndhir',
    'Dai',
    'Shafi',
    'Haad',
    'Mahd',
    'Maah',
    'Munji',
    'Naji',
    'Rasul',
    'Nabi',
    'Ummi',
    'Tihami',
    'Hashimi',
    'Abtahi',
    'Aziz',
    'Haris alaikum',
    'Rauf',
    'Rahim',
    'Taha',
    'Mujtaba',
    'Tasin',
    'Murtada',
    'Ha-mim',
    'Mustafa',
    'Ya-sin',
    'Aula',
    'Muzamil',
    'Wali',
    'Mudaththir',
    'Matin',
    'Musaddiq',
    'Tayyib',
    'Nasir',
    'Mansur',
    'Misbha',
    'Amir',
    'Hijazi',
    'Nazari',
    'Quraishi',
    'Mudari',
    'Nabi-at-tauba',
    'Hafiz',
    'Kamil',
    'Sadiq',
    'Amin',
    'Abdullah',
    'Kalim Allah',
    'Habib Allah',
    'Naji Allah',
    'Safi Allah',
    'Khatam al-anbia',
    'Hasib',
    'Mujib',
    'Shkor',
    'Muqtasid',
    'Rasal al-rahma',
    'Qawi',
    'Hafi',
    'Mamun',
    'Ma\'lum',
    'Haqq',
    'Mubin',
    'muti',
    'Awwal',
    'Akhir',
    'Zahir',
    'Batin',
    'Yatim',
    'Karim',
    'Hakim',
    'Sayyid',
    'Siraj',
    'Munir',
    'Muharram',
    'mukarram',
    'Mubashshir',
    'Mudakir',
    'Mutahhar',
    'Qarib',
    'Khalil',
    'Mad\'u',
    'Jawwad',
    'Khatim',
    'Adil',
    'Shahir',
    'Shahid',
    'Rasul al-malahim',
]

rasool_allah_names_english_meaning = [
    'Highly Praised',
    'The Most Commendable',
    'Praising',
    'Praised',
    'The father of Qasim',
    'The Latest',
    'The Victor',
    'The Witness',
    'The Awakener, The Gatherer',
    'The Guide',
    'He who is witnessed',
    'The Messenger of Good News',
    'Wamer',
    'The Caller',
    'Healer',
    'The Leader',
    'The Guided One',
    'The obliterator of Infidelity',
    'He who saves delivers',
    'Safe',
    'Massanger',
    'Prophet',
    'Unlettered',
    'From the Tihama',
    'Family of Hashim',
    'Belonging to al-Batha',
    'Nobel, Dear',
    'Full of concern for you',
    'Mild',
    'Merciful',
    'Surah 20:1',
    'Elect',
    'Surah 27:1',
    'Content',
    'Biginnig of surat 40:46',
    'chosen',
    'Sura 36:1',
    'Worthier, most worthy',
    'Wrapped',
    'Friend',
    'Covered',
    'Firm',
    'Who declares for true',
    'Good',
    'Helper',
    'Helped (by God)',
    'Lamp',
    'Prince, commander',
    'From the hijaz',
    'Of nazareth',
    'From the Clan quraish',
    'From the trib mudar',
    'Prophet of Repentance',
    'Preserver',
    'Perfect',
    'Sincere',
    'Trustworthy',
    'God\'s servant',
    'One Addressed by Allah',
    'God\'s beloved friend',
    'God\'s Intimate friend',
    'God\'s sincere friend',
    'Seal of the Prophet',
    'Respected',
    'Comping, Relying',
    'Most grateful',
    'Adopting a middle course',
    'The Messenger of mercy',
    'strong',
    'Wel-Informed',
    'Trusted',
    'wel-known',
    'Truth',
    'Clear,Evident',
    'Obident',
    'The First',
    'Last',
    'Outward,Externa',
    'Internel,Inner',
    'Orphan',
    'Generous',
    'Wise, Judicious',
    'Lord',
    'Lamp',
    'Radiant',
    'Forbiden, Immune',
    'Honored, Venerated',
    'Bringer of Good News',
    'Remember, Preacher',
    'Purified',
    'Near',
    'Good Friend',
    'Who Is Called',
    'Jenerous, Magnanimous',
    'Seal',
    'Justic',
    'Well-Known',
    'Witenessing, Martyr',
    'The Messenger of the Battles of Last Day',
]
